### ISSUE TITLE
issue with installing conda

### ISSUE THREAD

**Issue by kayanac** [wwood/CoverM#141] opened 2022-11-06 19:50 UTC
Hi,

I am having the following error while installing conda. Could you please help me with fixing this issue? 

--------------------------------------------------------------------------------------------------------------------
conda install coverm=0.6.1
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - coverm=0.6.1 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.17

**Comment by kayanac** [comment] 2022-11-06 19:53
I dont have any problem with installing version 0.4.0.

**Comment by wwood** [comment] 2022-11-06 22:18
Hi,

I would anticipate that the error you are seeing is caused by conflicts coverm has with other installed packages in your environment.

So would expect

conda create -n coverm coverm

Should work.

If there are other things in your env that are needed, then creating an environment with both might help pin down the issue.

Hth, ben

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT

________________________________

**Comment by kayanac** [comment] 2022-11-07 18:17
Hi Ben,

Thank you for your quick reply. I tried your suggestion but I am still having the same problem. As I said before I dont have any problem with installing older versions. The latest version is problematic.

Thanks,

Kadir

**Comment by wwood** [comment] 2022-11-10 02:11
Hi,

I tried this without issue - can you paste the command and output you are getting please?

```
$ mamba create -p /tmp/coverm coverm
...
To activate this environment, use

     $ mamba activate /tmp/coverm

To deactivate an active environment, use

     $ mamba deactivate

(miniconda3)b2:20221110:~$ conda activate /tmp/coverm
(coverm)b2:20221110:~$ coverm --version
coverm 0.6.1
```

**Comment by kayanac** [comment] 2022-11-10 12:46
Hi Ben,
When I used your command, it installed version 0.4.0 of coverm without any issue. Then I changed the command to "mamba create -p /tmp/coverm coverm=0.6.1" to install version 0.6.1 and I faced the error below:
"Looking for: ['coverm=0.6.1']

bioconda/linux-64                                           Using cache
bioconda/noarch                                             Using cache
pkgs/main/noarch                                   817.7kB @ 450.9kB/s  1.8s
pkgs/r/noarch                                        1.3MB @ 711.5kB/s  1.8s
pkgs/r/linux-64                                      1.4MB @ 773.4kB/s  1.9s
pkgs/main/linux-64                                   4.9MB @   2.0MB/s  2.6s
Encountered problems while solving:
  - nothing provides libzlib >=1.2.11,<1.3.0a0 needed by coverm-0.6.1-h1535e20_4"
 
But libzlib version 1.2.13 is already installed.

Thanks,

Kadir

**Comment by wwood** [comment] 2022-11-10 18:49
Hmm, what channels are you using?

I also don't understand what you mean by "But libzlib version 1.2.13 is already installed." When you create a new environment nothing is already installed right?


-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________

**Comment by kayanac** [comment] 2022-11-12 10:30
Hi Ben,

Problem solved. I changed the channel from bioconda to conda-forge and I did not have any issue with installing coverm 0.6.1. I used this command: " conda install -c conda-forge coverm=0.6.1" after creating the environment with "conda create -n coverm". 
Thanks,
Kadir

**Comment by wwood** [comment] 2022-11-12 10:48
Thanks for closing this out. I think you added condaforge not replaced bioconda, by doing that. Might pay to add condaforge to your condarc so don't have this problem with other software installs.

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________

**Closed** 2022-11-12 10:48 UTC
