### ISSUE TITLE
thread 'main' panicked at 'index out of bounds

### ISSUE THREAD

**Issue by slaperriere** [wwood/CoverM#17] opened 2020-02-02 19:01 UTC
Hello, 

I am getting the following error when I run coverm genome with an input of sorted BAM files and reference fasta.

[2020-02-02T18:33:54Z INFO  coverm] CoverM version 0.3.2
[2020-02-02T18:33:54Z INFO  coverm] Using min-covered-fraction 0%
[2020-02-02T18:33:54Z INFO  coverm] Using min-read-percent-identity 95%
[2020-02-02T18:33:54Z INFO  coverm] Using min-read-aligned-percent 95%
[2020-02-02T18:33:54Z INFO  coverm] Using min-read-percent-identity-pair 95%
[2020-02-02T18:33:54Z INFO  coverm] Using min-read-aligned-percent-pair 94%
[2020-02-02T18:33:54Z INFO  coverm] Not using directory entry 'must/fasta_files.txt' as a genome FASTA file, as it does not end with the extension 'fna'
[2020-02-02T18:33:54Z INFO  coverm] Reading contig names for 20 genomes ..
[2020-02-02T18:33:54Z INFO  coverm::genome] Of 20 reference IDs, 20 were assigned to a genome and 0 were not
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/slice/mod.rs:2723:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

Do you know what could be causing this error? Thank you!

**Comment by housw** [comment] 2020-02-04 17:31
same here: 

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/slice/mod.rs:2723:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by wwood** [comment] 2020-02-04 20:36
Hi,

No need to give the reference file when bam files are provided. This should be disallowed by the argument parser, I'll fix that.

Hope that helps? Ben
________________________________

**Comment by wwood** [comment] 2020-02-06 00:29
Hi again,

I just checked and it seems in 0.3.2, in `genome` mode I get this:

```
$ coverm genome --reference blah -b fdsa -c a.fq b.fq --separator o
...
error: The argument '--bam-files <bam-files>...' cannot be used with '--reference <reference>...'
```
So, the argument parser is disallowing it. And yet, you say you are running with 

> an input of sorted BAM files and reference fasta.

So, I'm confused - what was your command line exactly?
Thanks.

**Comment by housw** [comment] 2020-02-06 01:59
Hi Ben, 

thanks a lot for your prompt response, here is the command I'm using

```
coverm genome --bam-files ${bam_files} \
    --genome-fasta-extension "fa" \
    --genome-fasta-directory ${INPUT_GENOME_DIR} \
    --threads ${threads} \
    --min-read-aligned-length 30 \
    --min-read-percent-identity 0.95 \
    --min-read-aligned-percent 0.95 \
    --min-read-aligned-length-pair 30 \
    --min-read-percent-identity-pair 0.95 \
    --min-read-aligned-percent-pair 0.94 \
    --proper-pairs-only \
    --methods count length covered_bases covered_fraction reads_per_base mean variance trimmed_mean rpkm relative_abundance \
    --output-format dense \
    --min-covered-fraction 0 \
    --contig-end-exclusion 75 \
    --trim-min 0.05 \
    --trim-max 0.95 > ${coverM_RESULTS}/SPOT4YrMG_coverM_abundance.tsv 
```

please let me know if mis-understood anything. 

Thanks, 
Shengwei

**Comment by wwood** [comment] 2020-02-06 06:55
Hi,

I think I just fixed this - a problem with the variance estimator failing when no reads map to a contig. Are you able to download the master branch and confirm?

Thanks, ben

**Comment by housw** [comment] 2020-02-06 09:05
Hi Ben, 

thanks for the quick fix. I downloaded your master branch and gave it a try, unfortunately, I still got this error:

```
[2020-02-06T09:00:02Z INFO  coverm] CoverM version 0.3.2
[2020-02-06T09:00:02Z INFO  coverm] Using min-covered-fraction 0%
[2020-02-06T09:00:02Z INFO  coverm] Using min-read-percent-identity 95%
[2020-02-06T09:00:02Z INFO  coverm] Using min-read-aligned-percent 95%
[2020-02-06T09:00:02Z INFO  coverm] Using min-read-percent-identity-pair 95%
[2020-02-06T09:00:02Z INFO  coverm] Using min-read-aligned-percent-pair 94%
[2020-02-06T09:00:02Z INFO  coverm] Reading contig names for 24 genomes ..
[2020-02-06T09:00:02Z INFO  coverm::genome] Of 101 reference IDs, 101 were assigned to a genome and 0 were not
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/slice/mod.rs:2812:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Thanks a lot for your help! 

Shengwei

**Comment by wwood** [comment] 2020-02-06 14:12
Hmm, OK. Are you able to run the command again using `RUST_BACKTRACE=1 coverm genome --verbose ...` and give the output?

Actually I guess that'd be `RUST_BACKTRACE=1 cargo run -- genome --verbose ...` if you are running from the master branch.

Thanks.

**Comment by housw** [comment] 2020-02-06 18:32
Sure, here are the last several lines from the stdout: 

```
[2020-02-06T17:47:42Z DEBUG coverm::mosdepth_genome_coverage_estimators] Calculating coverage with unobserved [1160202], total bases 0, num_covered_bases 0, total_count 0, total_mismatches 0
[2020-02-06T17:47:42Z DEBUG coverm::mosdepth_genome_coverage_estimators] Calculating coverage with observed length 0, unobserved_length [1160202] and counts []
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/slice/mod.rs:2812:14
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:62
  14: <coverm::mosdepth_genome_coverage_estimators::CoverageEstimator as coverm::mosdepth_genome_coverage_estimators::MosdepthGenomeCoverageEstimator>::calculate_coverage
  15: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  16: coverm::genome::mosdepth_genome_coverage_with_contig_names
  17: coverm::main
  18: std::rt::lang_start::{{closure}}
  19: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  20: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  22: std::panicking::try
             at src/libstd/panicking.rs:270
  23: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  24: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  25: main
  26: __libc_start_main
  27: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Thanks!

**Comment by wwood** [comment] 2020-02-07 02:04
Hmm, since I don't see any line numbers there I don't think you are running in debug mode, which would help diagnose the issue quite a lot. Are you using `cargo run` ?

Also, that debug information is similar to before I fixed the issue. What commit are you using on the master branch?

Thanks.

**Comment by wwood** [comment] 2020-02-07 03:59
Hi,

In case it helps, I documented how to run the bleeding edge here:
https://github.com/wwood/CoverM/blob/master/README.md#development-version

**Comment by housw** [comment] 2020-02-07 07:10
Hi Ben, 

thanks a lot for the documentation, it helps. Now I can confirm that the error is triggered by the `variance` method, it works great if I remove it from the method list. 

Attached please find the detailed debug info. 

Cheers, 
Shengwei

[coverM_stdout_stderr.zip](https://github.com/wwood/CoverM/files/4169414/coverM_stdout_stderr.zip)

**Comment by housw** [comment] 2020-02-07 07:52
Okay, I think you've fixed it.

This is something related to my installation. When I run ` cargo install coverm --force` I thought it would replace the old version as it printed to the screen:

```
    Finished release [optimized] target(s) in 3m 07s
   Replacing /home/shengwei/.cargo/bin/coverm
   Replacing /home/shengwei/.cargo/bin/remove_minimap2_duplicated_headers
    Replaced package `coverm v0.3.2` with `coverm v0.3.2` (executables `coverm`, `remove_minimap2_duplicated_headers`)
```

but it didn't. I replaced it with the compiled file found in `target/debug/coverm` solved the problem. 


Thanks a lot for your help. Please close it. 

Cheers, 
Shengwei

**Comment by wwood** [comment] 2020-02-07 22:09
OK, great. Thanks for the detailed report.

**Closed by wwood** 2020-02-07 22:09 UTC
