### ISSUE TITLE
samtools sort fail cannot allocate memory

### ISSUE THREAD

**Issue by jianshu93** [wwood/CoverM#89] opened 2021-09-08 14:06 UTC
Hello Ben, 

When mapping a very big metagenome I have the following error:

[2021-09-08T13:51:56Z ERROR coverm::bam_generator] The STDERR for the samtools sort part was: samtools sort: failed to create temporary file "/scratch/2761572.sched-torque.pace.gatech.edu/coverm_fifo.qCoPiHLFzumr/coverm-make-samtools-sortqdXfkh.0003.bam": Cannot allocate memory
    samtools sort: failed to create temporary file "/scratch/2761572.sched-torque.pace.gatech.edu/coverm_fifo.qCoPiHLFzumr/coverm-make-samtools-sortqdXfkh.0010.bam": Cannot allocate memory
    samtools sort: failed to create temporary file "/scratch/2761572.sched-torque.pace.gatech.edu/coverm_fifo.qCoPiHLFzumr/coverm-make-samtools-sortqdXfkh.0011.bam": Cannot allocate memory
    samtools sort: failed to create temporary file "/scratch/2761572.sched-torque.pace.gatech.edu/coverm_fifo.qCoPiHLFzumr/coverm-make-samtools-sortqdXfkh.0014.bam": Cannot allocate memory
    
[2021-09-08T13:51:56Z ERROR coverm::bam_generator] Cannot continue since mapping failed.

I suspect it is because samtools sort 2.13 or newer automatically allocated 768 M max memory for each thread, I am using 24 thread.  You may need to add the samtools sort max memory option to coverm contig/genome.

Thanks,

Jianshu

**Comment by wwood** [comment] 2021-09-09 07:00
Hi Jianshu,

Can you confirm that the issue is caused by excessive memory consumption rather than running out of disk space in `/scratch/2761572.sched-torque.pace.gatech.edu/` e.g. does it work when you use less threads?

Thanks.

**Comment by jianshu93** [comment] 2021-09-09 13:28
Hello Ben,

It's not solved even add TMPDIR=. before coverm. I have more than 10 T in my current directory but I still have:

**Comment by jianshu93** [comment] 2021-09-12 02:41
it turns out that our super computer job manage system is responsible for this. the torque system does not allow samtools to allocate such big amount of memory for 24 thread. 12 threads works. thanks！

jianshu

**Comment by wwood** [comment] 2021-09-12 03:00
OK, great. I think RAM usage overall is maybe something that would have to be confronted as a whole e.g. including the mapping step which runs at the same time as samtools sort. It isn't entirely clear though that such a task would be particularly useful in the general case because it depends on database size. So I think I'll close this and take no action.

Thanks for following up.
ben

**Closed by wwood** 2021-09-12 03:00 UTC
